#!/usr/bin/env python3
"""
generate_report.py - consolidates suggestions.json (and, if present,
the AI-enriched suggestions_ai.json) into a single human-readable
Markdown report for a scanned target.

Usage:
    python3 generate_report.py <target_dir> --out <report.md>

Example:
    python3 generate_report.py targets/10.0.0.5 --out targets/10.0.0.5/reports/report.md
"""

import argparse
import json
import os
import sys
from datetime import datetime


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("target_dir", help="Target output directory (e.g. targets/10.0.0.5)")
    p.add_argument(
        "--out",
        default=None,
        help="Report output path (default: <target_dir>/reports/report.md)",
    )
    return p.parse_args()


def load_json(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def find_suggestions_file(target_dir):
    """Prefers the AI-enriched file if it exists, otherwise falls back
    to the static (non-AI) suggestions file produced by parse_nmap.py.

    Returns a tuple: (path_or_None, used_ai: bool)
    """
    ai_path = os.path.join(target_dir, "enum", "suggestions_ai.json")
    static_path = os.path.join(target_dir, "enum", "suggestions.json")

    if os.path.isfile(ai_path):
        return ai_path, True
    if os.path.isfile(static_path):
        return static_path, False

    return None, False


def format_port_section(port_info):
    """Builds the Markdown block for a single open port: header, detected
    service info, AI analysis (if any), and the suggestions table."""
    lines = []

    header = (
        f"### Port {port_info['port']}/{port_info.get('protocol', 'tcp')} "
        f"- {port_info.get('service', 'unknown')}"
    )
    lines.append(header)

    product = port_info.get("product", "")
    version = port_info.get("version", "")
    if product or version:
        lines.append(f"**Detected:** {product} {version}".strip())

    ai_analysis = port_info.get("ai_analysis")
    if ai_analysis:
        lines.append(f"\n**AI analysis:** {ai_analysis}")

    suggestions = port_info.get("suggestions", [])
    if suggestions:
        lines.append("\n**Suggested next steps:**\n")
        lines.append("| Tool | Command | Description |")
        lines.append("|------|---------|-------------|")
        for s in suggestions:
            tool = s.get("tool", "-")
            command = s.get("command") or "-"
            description = s.get("description", "-")
            command_display = f"`{command}`" if command != "-" else "-"
            lines.append(f"| {tool} | {command_display} | {description} |")

    ai_commands = port_info.get("ai_recommended_commands")
    if ai_commands:
        lines.append("\n**AI-recommended commands:**")
        for c in ai_commands:
            lines.append(f"- `{c}`")

    if not suggestions and not ai_commands:
        lines.append("\n_No suggestions available for this port._")

    return "\n".join(lines)


def generate_markdown(data, used_ai):
    """Builds the full Markdown document from the parsed suggestions data."""
    target = data.get("target", "unknown")
    hosts = data.get("hosts", [])
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# Reconnaissance Report - {target}",
        f"*Generated on {timestamp}*",
        "",
        "> Automatically generated by recon-framework. "
        "Use only against targets you are explicitly authorized to test.",
        "",
    ]

    total_hosts = len(hosts)
    total_ports = sum(len(h.get("open_ports", [])) for h in hosts)
    lines.append(f"**Summary:** {total_hosts} host(s) scanned, {total_ports} open port(s) found.")
    if used_ai:
        lines.append("**AI enrichment:** enabled for this report.")
    lines.append("")

    for host in hosts:
        lines.append(f"## Host: {host.get('address', 'unknown')}")

        ports = host.get("open_ports", [])
        if not ports:
            lines.append("_No open ports found._\n")
            continue

        lines.append("")
        lines.append("| Port | Protocol | Service | Product | Version |")
        lines.append("|------|----------|---------|---------|---------|")
        for p in ports:
            lines.append(
                f"| {p['port']} | {p.get('protocol', '')} | {p.get('service', '')} "
                f"| {p.get('product', '')} | {p.get('version', '')} |"
            )
        lines.append("")

        for p in ports:
            lines.append(format_port_section(p))
            lines.append("")

    ai_overall = data.get("ai_overall")
    if ai_overall:
        lines.append("## Overall AI Assessment")
        priority = ai_overall.get("priority_order", [])
        if priority:
            lines.append(f"**Priority order (by port):** {', '.join(str(p) for p in priority)}")
        attack_path = ai_overall.get("attack_path", "")
        if attack_path:
            lines.append(f"\n**Suggested attack path:** {attack_path}")
        lines.append("")

    return "\n".join(lines)


def main():
    args = parse_args()

    suggestions_path, used_ai = find_suggestions_file(args.target_dir)
    if suggestions_path is None:
        print(f"[report] No suggestions file found under {args.target_dir}/enum/", file=sys.stderr)
        sys.exit(1)

    try:
        data = load_json(suggestions_path)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        print(f"[report] Could not read {suggestions_path}: {exc}", file=sys.stderr)
        sys.exit(1)

    report_md = generate_markdown(data, used_ai)

    out_path = args.out or os.path.join(args.target_dir, "reports", "report.md")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(report_md)

    print(f"[report] Report built from: {suggestions_path}")
    print(f"[report] Saved to: {out_path}")


if __name__ == "__main__":
    main()