#!/usr/bin/env python3
"""
parse_nmap.py - reads the XML generated by nmap and suggests next tools
for each discovered port/service.

Usage:
    python3 parse_nmap.py <scan.xml> --out <suggestions.json> --target <target>
"""

import argparse
import json
import os
import sys
import xml.etree.ElementTree as ET

# Simple map: port or service name -> suggested next steps.
# This will grow as the project evolves (step 3: actually triggering
# these tools automatically from Bash).
DEFAULT_SUGGESTIONS_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "suggestions.json"
)

def load_suggestions(path):
    """Load the port -> list of suggestions mapping from an external JSON file.

    The keys in the JSON file are strings (e.g. "80"), since JSON does not allow
    integer keys. Here, they are converted to integers because nmap reports
    ports as numbers (portid), allowing direct lookup in build_suggestions().
    """
    try:
        with open(path, "r", encoding="utf-8") as fh:
            raw = json.load(fh)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        print(f"[parser] Aviso: não foi possível carregar {path}: {exc}", file=sys.strderr)
        print(f"[parser] Continuando sem sugestões.", file=sys.stderr)
        return {}

    return {int(port_str): commands for port_str, commands in raw.items()}

def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xml_path", help="Path to the scan.xml file produced by nmap")
    p.add_argument("--out", required=True, help="Output JSON file")
    p.add_argument("--target", required=True, help="Target (IP/domain), for context in the report")
    p.add_argument(
        "--suggestions-file",
        default=DEFAULT_SUGGESTIONS_FILE,
        help=f"Arquivo JOSN com o mapa porta->sugestão (default: {DEFAULT_SUGGESTIONS_FILE})",
    )
    return p.parse_args()


def parse_nmap_xml(xml_path):
    """Extracts host(s), open ports, service, and version from the nmap XML."""
    tree = ET.parse(xml_path)
    root = tree.getroot()

    hosts = []
    for host_el in root.findall("host"):
        addr_el = host_el.find("address")
        address = addr_el.get("addr") if addr_el is not None else "unknown"

        ports = []
        ports_el = host_el.find("ports")
        if ports_el is not None:
            for port_el in ports_el.findall("port"):
                state_el = port_el.find("state")
                if state_el is None or state_el.get("state") != "open":
                    continue

                portid = int(port_el.get("portid"))
                protocol = port_el.get("protocol")

                service_el = port_el.find("service")
                service_name = service_el.get("name") if service_el is not None else "unknown"
                product = service_el.get("product", "") if service_el is not None else ""
                version = service_el.get("version", "") if service_el is not None else ""

                ports.append({
                    "port": portid,
                    "protocol": protocol,
                    "service": service_name,
                    "product": product,
                    "version": version,
                })

        hosts.append({"address": address, "open_ports": ports})

    return hosts


def build_suggestions(hosts, suggestions_map):
    """For each open port, attach suggested next steps."""
    for host in hosts:
        for port_info in host["open_ports"]:
            suggestions = suggestions_map.get(port_info["port"], [])
            port_info["suggestions"] = suggestions
    return hosts


def main():
    args = parse_args()

    try:
        hosts = parse_nmap_xml(args.xml_path)
    except (ET.ParseError, FileNotFoundError) as exc:
        print(f"[error] Could not read {args.xml_path}: {exc}", file=sys.stderr)
        sys.exit(1)

    suggestions_map = load_suggestions(args.suggestions_file)
    hosts = build_suggestions(hosts, suggestions_map)

    result = {"target": args.target, "hosts": hosts}

    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2, ensure_ascii=False)

    total_ports = sum(len(h["open_ports"]) for h in hosts)
    print(f"[parser] {len(hosts)} host(s) analyzed, {total_ports} open port(s).")
    print(f"[parser] Suggestions saved to {args.out}")


if __name__ == "__main__":
    main()